### PR TITLE
Instructions for fixing vcruntime140.dll error

### PR DESCRIPTION
**Pull request by gkeegan**
See #36.

### CODE REVIEW

**Comment by gkeegan** [comment]
Hey @JibbSmart , any interest in merging this or does the new release fix it?

**Comment by JibbSmart** [comment]
Sorry, I should've thought to shoot you a message. I'm hopeful the new release has fixed it. I can't know for sure from my end, though

**Comment by gkeegan** [comment]
It appears like it is fixed, since I did not get an error on launch. I'll close this and the issue associated. Great work!

**Comment by JibbSmart** [comment]
I'm so glad to hear that. @kicsyromy swooped in and drastically improved the build process, so this shouldn't be an issue again. Thanks for checking!

**Pull request closed without merging**
