### PR TITLE
Port to Linux

### PR DESCRIPTION
**Pull request by kicsyromy**
- Add CMake build system generator for both Windows and Linux, tested on Windows 10 VS 2017 and 2019, Ubuntu 20.04 and Archlinux
- Download master branch of JSL at configure time and build with JSM
- Implement InputHeleper with Linux variants where applicable and adapt Windows builds where needed
- Create abstract version of TrayIcon and create Linux implementation using StatusNotifierItem, also rename/move Windows implementation to WindowsTrayIcon.h/.cpp
- Add PlatformDefinitions.h/.cpp and add platform specific constants, headers/functions to it
- Add dummy implementation of Whitelister for Linux
- Normalize std::wstring and std::string usage behind UnicodeString typedef and U() macro
- Normalize paths for loading configurations and Autoload-ed configurations using runtime initialized AUTOLOAD_FOLDER, GYRO_CONFIGS_FOLDER, BASE_JSM_CONFIG_FOLDER using platform-specific paths (.exe folder on Windows, and XDG_CONFIG_HOME on Linux)

### CODE REVIEW

**Comment by kicsyromy** [comment]
Hi @JibbSmart I've starting working on porting over the main app to Linux as well.

I would like to discuss how you think it's best to proceed, since a lot of WIN32 stuff is scattered around the code-base.

There is also the question of sharing code between platforms which isn't really doable (as far as I can tell) with the current file structure, for instance, I've reused most of the logic in InputHelpers for the Linux implementation, but currently that means copy-paste :disappointed: 
Perhaps some form of (compile-time/light) abstraction would be nice here (in InputHelpers), as well as the tray icon and the whitelister, both of which also need to be ported over. An abstraction layer would also help reduce the number of #ifdefs (yuck) in the main.cpp file.

Please let me know if I'm a good path or not. Great project :grin:

**Comment by JibbSmart** [comment]
Hi @kicsyromy thanks for getting involved!

I appreciate you being pro-active and getting started right away. I'd love for JoyShockMapper to work on Linux. You're right, WIN32 is scattered about a bit -- it was originally intended to be all in its own file (inputHelpers), but as you can see that has changed. @Electronicks is working on a big refactor, and this is something for us to be mindful of -- let's have a discussion about that here.

One of the goals of JoyShockMapper is to minimize dependencies and avoid bloat. The more 3rd party libraries involved, the harder it can be for us to maintain, or for newcomers to get into it. It's very hard to remove a dependency once we're relying on it. @Electronicks can attest that I'd strongly err on the side of avoiding 3rd party libraries and dependencies. With that in mind, what's the purpose of tiny-process-library, and can we manage without it?

Omitting the Whitelisting and Tray features to start off is a good idea, I think. They're useful features, but JoyShockMapper works without them and that'll make things easier. First priority is for this to just work.

In terms of abstraction, let's say we have inputHelpersWin and inputHelpersLinux. Let each of those files assume they're only going to be included on their platform (no platform-checking #ifdefs in there). Then in main (or wherever they're used, use #ifdefs to choose which of the files to use. Where both inputHelpers* have code they could share, they can both #include the same inputHelpersShared (for example). We should try to extract as much as we can into inputHelpersShared and keep platform-specific code to a minimum.

How does that sound?

Also, if you don't mind, trying to stick to the "style" of the code that's already there is helpful -- even though JSM doesn't really have a strongly enforced style. Aesthetic changes might feel productive in the moment, but can make merging harder if someone else is working on the project at the same time.

What made me think of this was things like adding a "std::" in front of max and min, where I don't think it's very important. If you think it is, let's have a discussion about that before changing it :)

The other example that's easy to miss is using spaces for indenting where the project uses tabs. I know some people feel strongly about tabs vs spaces, and I really don't care at a project level. But the consistent answer is the right answer, and I believe JSM currently uses tabs for indenting.

I'd love to hear your thoughts, and feel free to push back on anything you don't agree with. And I'm glad to have you involved!
Cheers :)

**Comment by kicsyromy** [comment]
Hello, I've replied to your suggestions inline to make the conversation easier to follow.

> Hi @kicsyromy thanks for getting involved!
> 
> I appreciate you being pro-active and getting started right away. I'd love for JoyShockMapper to work on Linux. You're right, WIN32 is scattered about a bit -- it was originally intended to be all in its own file (inputHelpers), but as you can see that has changed. @Electronicks is working on a big refactor, and this is something for us to be mindful of -- let's have a discussion about that here.
> 
Thanks for bringing this up, very useful info.
> One of the goals of JoyShockMapper is to minimize dependencies and avoid bloat. The more 3rd party libraries involved, the harder it can be for us to maintain, or for newcomers to get into it. It's very hard to remove a dependency once we're relying on it. @Electronicks can attest that I'd strongly err on the side of avoiding 3rd party libraries and dependencies. With that in mind, what's the purpose of tiny-process-library, and can we manage without it?
>
Fair point. Yes, we can surely live without it since we can just use POSIX directly. I only used it here to apply some permissions when setting up the virtual keyboard and mouse, but since this is a workaround anyway, I would like to get rid of it altogether before the final merge.

> Omitting the Whitelisting and Tray features to start off is a good idea, I think. They're useful features, but JoyShockMapper works without them and that'll make things easier. First priority is for this to just work.
>
Agreed!

> In terms of abstraction, let's say we have inputHelpersWin and inputHelpersLinux. Let each of those files assume they're only going to be included on their platform (no platform-checking #ifdefs in there). Then in main (or wherever they're used, use #ifdefs to choose which of the files to use. Where both inputHelpers* have code they could share, they can both #include the same inputHelpersShared (for example). We should try to extract as much as we can into inputHelpersShared and keep platform-specific code to a minimum.
> 
> How does that sound?
>
Exactly how I imagined it should be done. Sounds good.

> Also, if you don't mind, trying to stick to the "style" of the code that's already there is helpful -- even though JSM doesn't really have a strongly enforced style. Aesthetic changes might feel productive in the moment, but can make merging harder if someone else is working on the project at the same time.
>
I only noticed this morning that my editor automatically changed all the tabs to spaces (whoops), pushed a second change to revert where it wasn't needed.
In this regard I would love to have a .clang-format file that we use throughout the project. This would be nice since all modern C++ editors support formatting using a .clang-format file, Visual Studio, VSCpde, QtCreator and CLion at the very least. And can also be used for formatting using (N)Vim and Emacs.

> What made me think of this was things like adding a "std::" in front of max and min, where I don't think it's very important. If you think it is, let's have a discussion about that before changing it :)
>
The std:: was actually not a stylistic choice but it was needed to make the code compile :), both clang and GCC refused to build with min instead of std::min my guess is it was trying to use C's min() instead of C++'s min, which could be intentional on your part or not (in which case it could be a bug).

> The other example that's easy to miss is using spaces for indenting where the project uses tabs. I know some people feel strongly about tabs vs spaces, and I really don't care at a project level. But the consistent answer is the right answer, and I believe JSM currently uses tabs for indenting.
>
I am fine with whatever the project decides on, it's just my editors defaults that are messing this up for me. Also see my comment from above with regards to clang-format.

> I'd love to hear your thoughts, and feel free to push back on anything you don't agree with. And I'm glad to have you involved!
> Cheers :)
>
Thank you, very nice to see you so open to collaboration :)

On a different note it's very important to me that I don't overstep any boundaries, so I'm trying to keep changes in existing code to a minimum so I'll post further questions here when I hit them.

Have a good one :)

**Comment by kicsyromy** [comment]
Hi again,

I have a few more questions, I stared with CMake as the build system generator, since that's what I'm most familiar with, do you have any preference in this regard? In it's current shape it's very easy to swap out for meson, premake or whatever if you would like.
And secondly, what is the motivation behind using .cpp file as a header, in this case inputHelpers.cpp?

**Comment by JibbSmart** [comment]
Hi!

CMake seems fine to me. I don't have a particular preference, so let's go with that.

Regarding using inputHelpers.cpp rather than inputHelpers.h, I haven't done a lot of C++ at large scales and so I'm not clear on the distinction here. My understanding was ".h" should be used for declaring interfaces and function prototypes while implementations go in ".cpp" files. Since inputHelpers is pretty small and I originally wanted to keep it to relatively few files (though it has grown and the refactor will involve splitting the program into more files), I figured I'd have it all in one file, and ".cpp" made the most sense to me. You reckon it should be ".h" instead?

**Comment by kicsyromy** [comment]
>Regarding using inputHelpers.cpp rather than inputHelpers.h, I haven't done a lot of C++ at large scales and so I'm not clear on the distinction here. My understanding was ".h" should be used for declaring interfaces and function prototypes while implementations go in ".cpp" files. Since inputHelpers is pretty small and I originally wanted to keep it to relatively few files (though it has grown and the refactor will involve splitting the program into more files), I figured I'd have it all in one file, and ".cpp" made the most sense to me. You reckon it should be ".h" instead?
>
Not necessarily, a #include is (in a somewhat reductive sense) a copy-paste. In general yes, declarations are done in a header file while implementations are done in a source file. But this is in no way enforced and there are very valid reasons (inlining templates, constexpr functions) to write the implementation of a class or function solely in a header file.

In this case to make the purpose of the file clear within the project in would be a good idea to make it an .h file.

**Comment by Electronicks** [comment]
Hi @kicsyromy , creating a header file for inputHelper.cpp would be important and is part of the refactoring I'm working on.

Another possibility regarding cross-platform (I have a bit of experience in that field) is to define a single platform-agnostic header for inputHelpers and implement in different ways in two different cpp files, either of which would be included depending on platform.

Also, @JibbSmart if we use cmake on linux, should we use it on Windows as well? Basically it's a script that will generate the sln file for lvisual studio instead of having it checked in the repo? I can help with setting it up. This enables better coherence between versions.

**Comment by kicsyromy** [comment]
Hi @Electronicks 

> Hi @kicsyromy , creating a header file for inputHelper.cpp would be important and is part of the refactoring I'm working on.
> 
> Another possibility regarding cross-platform (I have a bit of experience in that field) is to define a single platform-agnostic header for inputHelpers and implement in different ways in two different cpp files, either of which would be included depending on platform.
> 
This is exactly what I was thinking of, and what I meant when I said some sort of abstraction in my initial comment. In this case the build system (CMake) would decide which source file to compile based on the target platform.

> Also, @JibbSmart if we use cmake on linux, should we use it on Windows as well? Basically it's a script that will generate the sln file for lvisual studio instead of having it checked in the repo? I can help with setting it up. This enables better coherence between versions.
>
I would second this since it should make (pun not intended) build system maintenance much easier, and could also prevent platform-specific bugs.

**Comment by kicsyromy** [comment]
Hi guys,

I've pushed some changes mostly with regards to how I would arrange the platform-specific stuff and how I would set up the build system's and general file structure.

When you have a chance, have a look, and see if it's OK with you.

Just to give you an idea this is what it looks like in a file manager:
JoyShockMapper_fs_layout


@Electronicks I saw you split out the code from inputHelpers to a separate header file, I also did this myself, when your changes are merged I'll take them and adapt what I did.

P.S. For the time being please ignore the whitespace-related changes, I'll fix those before merging

**Comment by JibbSmart** [comment]
Great! I was about to ask you two how best to accommodate both pull requests. I'll merge @Electronicks' request now.

@kicsyromy Do you use Discord? There's a lot of JSM-related discussion on the Gyro Gaming Discord ( https://discord.gg/b4nAm6F ) and I'm setting up a JSM-developers-only channel so we can more easily coordinate. If and when you do join, let me know and I'll give you the appropriate role to give you access to the channel.

Obviously you joining the server and the channel doesn't require any commitment to keep working on JSM, and you can contribute as little or as much as you want :)

**Comment by Electronicks** [comment]
The file structure looks good to me. I had inputHelper renamed with the Win suffix, but your solution is better IMO.

**Comment by kicsyromy** [comment]
> Great! I was about to ask you two how best to accommodate both pull requests. I'll merge @Electronicks' request now.
> 
> @kicsyromy Do you use Discord? There's a lot of JSM-related discussion on the Gyro Gaming Discord ( https://discord.gg/b4nAm6F ) and I'm setting up a JSM-developers-only channel so we can more easily coordinate. If and when you do join, let me know and I'll give you the appropriate role to give you access to the channel.
> 
> Obviously you joining the server and the channel doesn't require any commitment to keep working on JSM, and you can contribute as little or as much as you want :)
>
I've resurrected my old Discord account, and sent you a PM.

Thanks!

**Pull request merged**
