### PR TITLE
Added FLICK_DEADZONE_ANGLE setting

### PR DESCRIPTION
**Pull request by rstraver**
Hi Jibb,

About a month ago I requested a forward angle deadzone (in the youtube comment section) to help ignore small movements when moving the stick forward. I had some time to look into it today and this seems to do the trick.

Angles are in radians (no need to calculate extra stuff), this is probably a nice value to start out with:
```
FLICK_DEADZONE_ANGLE = 0.25 # Roughly 15 degrees
```

It's been a while since I wrote c++ and I'm not 100% sure on whether all my edits were required/in the right spots but I followed some other settings and this seemed the general way to do it.

Let me know if I messed up or should properly check something.

### CODE REVIEW

**Comment by JibbSmart** [comment]
Hi! Thanks so much for doing that! It mostly looks good. I'd just ask that you make it degrees instead of radians. The gyro thresholds are all in degrees per second, and the traditional stick turning is in degrees per second, so I think degrees fits better. Besides that, at first blush it looks great, and I appreciate the contribution!

**Comment by JibbSmart** [comment]
Also, what name would you like to go by in the changelog?

**Comment by rstraver** [comment]
Alright, I just multiplied the values at the variable comparison. If there's a more elegant way I'd love to know but I couldn't find a "variable conversion" step at the time of parsing the settings file.

I also added a line to the filters bit but I honestly have no clue if I picked the right filter for this one:
```
	flick_deadzone_angle.SetFilter(&filterFloat);
```

About the changelog name thing, what's the usual here? Real names or nicknames? I don't want to be the odd one out here ;).

Additionally, is there some roadmap/feature planning somewhere that I can look into? This project seems something I'd like to play around testing a few things with every now and then, perhaps I can do some useful stuff while I'm at it.

**Comment by rstraver** [comment]
Also, please ignore my editor's OCD on the whitespace removal, those edits were not intentional (and completely behind my back, really...)

**Comment by JibbSmart** [comment]
We have first names ("Nicolas", "Bryan") aliases ("Jibb", "Contributer"), full name ("Romeo Calota"). Whichever style you prefer :)
Yes, just converting the angle at comparison is great. I'll merge this in once I have your preferred credit name

**Comment by rstraver** [comment]
Considering my github username I'd say just go with my full name then: Roy Straver
Thanks for the credit ;)

**Comment by JibbSmart** [comment]
Great! Nice work!

**Pull request merged**
